services:
  megamanapi:
    image: ${ DOCKER_REGISTRY- }megamanapi
    container_name: megamanapi
    build:
      context:
        dockerfile: Api/dockerfile
    depends_on:
    - sqlserver
    ports:
    - "3000:80"
    restart: always
    environment:
    - ASPNETCORE_ENVIRONMENT=Development

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "SqlP@ssw0rd!1"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    volumes:
      - ./database_structure.sql:/tmp/01-database_structure.sql
      - ./02-table_data.sql:/tmp/02-table_data.sql
      - ./init-api.sh:/tmp/init-api.sh
    command: /bin/bash ./tmp/init-api.sh